# Generated by Django 6.0.2 on 2026-07-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("employee", "Employee"),
                    ("employer", "Employer"),
                    ("other", "Other"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]


