# Generated by Django 4.2.7 on 2026-07-13 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                (
                    "work_type",
                    models.CharField(
                        choices=[("physical", "On-Site"), ("remote", "Remote")],
                        default="physical",
                        max_length=20,
                    ),
                ),
                ("apply_url", models.URLField(blank=True, max_length=500)),
                ("company_website", models.URLField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_urgent", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("unique_views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("applications_count", models.PositiveIntegerField(default=0)),
                ("is_user_submitted", models.BooleanField(default=False)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("temporary", "Temporary"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry Level (0-2 years)"),
                            ("mid", "Mid Level (2-5 years)"),
                            ("senior", "Senior Level (5-8 years)"),
                            ("lead", "Lead/Manager (8+ years)"),
                            ("executive", "Executive (10+ years)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(blank=True, default="USD", max_length=3),
                ),
                (
                    "salary_period",
                    models.CharField(
                        blank=True,
                        choices=[("yearly", "Per Year"), ("monthly", "Per Month")],
                        default="yearly",
                        max_length=20,
                    ),
                ),
                (
                    "benefits",
                    models.TextField(
                        blank=True,
                        help_text="List benefits like health insurance, 401k, etc.",
                    ),
                ),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "shift_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "Morning Shift"),
                            ("afternoon", "Afternoon Shift"),
                            ("evening", "Evening Shift"),
                            ("night", "Night Shift"),
                            ("flexible", "Flexible"),
                            ("weekend", "Weekend Only"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "hours_per_week",
                    models.PositiveIntegerField(
                        blank=True, help_text="Hours per week", null=True
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_range",
                    models.CharField(
                        blank=True, help_text="e.g., $15-20/hour", max_length=100
                    ),
                ),
                ("currency", models.CharField(blank=True, default="USD", max_length=3)),
                ("is_flexible_schedule", models.BooleanField(default=False)),
                ("is_weekend_available", models.BooleanField(default=False)),
                ("is_immediate", models.BooleanField(default=False)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "working_hours",
                    models.CharField(
                        blank=True, help_text="e.g., 9 AM - 5 PM", max_length=100
                    ),
                ),
                ("is_immediate_joining", models.BooleanField(default=False)),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Fixed Price"),
                            ("hourly", "Hourly Rate"),
                            ("milestone", "Milestone Based"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "contract_currency",
                    models.CharField(blank=True, default="USD", max_length=3),
                ),
                (
                    "contract_experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry Level (0-2 years)"),
                            ("mid", "Mid Level (2-5 years)"),
                            ("senior", "Senior Level (5-8 years)"),
                            ("lead", "Lead/Manager (8+ years)"),
                            ("executive", "Executive (10+ years)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "duration_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("short", "Short Term (1-3 months)"),
                            ("medium", "Medium Term (3-6 months)"),
                            ("long", "Long Term (6+ months)"),
                            ("ongoing", "Ongoing"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "estimated_duration",
                    models.CharField(
                        blank=True, help_text="e.g., 3 months, 6 months", max_length=100
                    ),
                ),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                ("is_contract_remote", models.BooleanField(default=False)),
                ("is_contract_urgent", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="categories.category",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="JobView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referer", models.URLField(blank=True, max_length=500)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_logs",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="JobComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("apply", "Apply Link"),
                            ("website", "Company Website"),
                        ],
                        max_length=20,
                    ),
                ),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_logs",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                (
                    "work_type",
                    models.CharField(
                        choices=[("physical", "On-Site"), ("remote", "Remote")],
                        default="physical",
                        max_length=20,
                    ),
                ),
                ("apply_url", models.URLField(blank=True, max_length=500)),
                ("company_website", models.URLField(blank=True)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Notes from admin"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("temporary", "Temporary"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry Level (0-2 years)"),
                            ("mid", "Mid Level (2-5 years)"),
                            ("senior", "Senior Level (5-8 years)"),
                            ("lead", "Lead/Manager (8+ years)"),
                            ("executive", "Executive (10+ years)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(blank=True, default="USD", max_length=3),
                ),
                (
                    "salary_period",
                    models.CharField(
                        blank=True,
                        choices=[("yearly", "Per Year"), ("monthly", "Per Month")],
                        default="yearly",
                        max_length=20,
                    ),
                ),
                ("benefits", models.TextField(blank=True)),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "shift_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "Morning Shift"),
                            ("afternoon", "Afternoon Shift"),
                            ("evening", "Evening Shift"),
                            ("night", "Night Shift"),
                            ("flexible", "Flexible"),
                            ("weekend", "Weekend Only"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("hours_per_week", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("salary_range", models.CharField(blank=True, max_length=100)),
                ("currency", models.CharField(blank=True, default="USD", max_length=3)),
                ("is_flexible_schedule", models.BooleanField(default=False)),
                ("is_weekend_available", models.BooleanField(default=False)),
                ("is_immediate", models.BooleanField(default=False)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("working_hours", models.CharField(blank=True, max_length=100)),
                ("is_immediate_joining", models.BooleanField(default=False)),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Fixed Price"),
                            ("hourly", "Hourly Rate"),
                            ("milestone", "Milestone Based"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "contract_currency",
                    models.CharField(blank=True, default="USD", max_length=3),
                ),
                (
                    "contract_experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry Level (0-2 years)"),
                            ("mid", "Mid Level (2-5 years)"),
                            ("senior", "Senior Level (5-8 years)"),
                            ("lead", "Lead/Manager (8+ years)"),
                            ("executive", "Executive (10+ years)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "duration_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("short", "Short Term (1-3 months)"),
                            ("medium", "Medium Term (3-6 months)"),
                            ("long", "Long Term (6+ months)"),
                            ("ongoing", "Ongoing"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("estimated_duration", models.CharField(blank=True, max_length=100)),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                ("is_contract_remote", models.BooleanField(default=False)),
                ("is_contract_urgent", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categories.category",
                    ),
                ),
                (
                    "created_job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_application",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
                "unique_together": {("user", "job")},
            },
        ),
        migrations.CreateModel(
            name="JobLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_log",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("job", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active", "posted_at"], name="jobs_job_is_acti_2e803c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["work_type"], name="jobs_job_work_ty_4ebff2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["category"], name="jobs_job_categor_24d294_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["company"], name="jobs_job_company_73ae7f_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["employment_type"], name="jobs_job_employm_743f88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["expires_at"], name="jobs_job_expires_1dbc32_idx"
            ),
        ),
    ]
