# Generated by Django 5.2.6 on 2026-08-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[("fixed", "Fixed Price"), ("hourly", "Hourly Rate")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("daily_wage", "Daily Wage"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("physical", "On-Site"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                default="physical",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[("fixed", "Fixed Price"), ("hourly", "Hourly Rate")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("daily_wage", "Daily Wage"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("physical", "On-Site"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                default="physical",
                max_length=20,
            ),
        ),
    ]
