# Generated by Django 4.2.7 on 2026-07-14 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('stipend', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('physical', 'Physical'), ('remote', 'Remote')], max_length=20)),
                ('internship_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time')], default='full_time', help_text='Full-Time or Part-Time internship', max_length=20)),
                ('apply_url', models.URLField(blank=True, max_length=500)),
                ('company_website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('is_user_submitted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internships', to='categories.category')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_internships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='internships.internship')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='internships.internship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_internships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'internship')},
            },
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['is_active', 'posted_at'], name='internships_is_acti_5f99a6_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['type'], name='internships_type_07b502_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['internship_type'], name='internships_interns_88e740_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['category'], name='internships_categor_51260d_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['company'], name='internships_company_83aaf7_idx'),
        ),
    ]
