# Generated by Django 4.2.7 on 2026-07-13 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("internships", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternshipView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referer", models.URLField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.AddField(
            model_name="internship",
            name="applications_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="internship",
            name="clicks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="internship",
            name="internship_type",
            field=models.CharField(
                choices=[("full_time", "Full-Time"), ("part_time", "Part-Time")],
                default="full_time",
                help_text="Full-Time or Part-Time internship",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="is_user_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="internship",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="internship",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posted_internships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="internship",
            index=models.Index(
                fields=["is_active", "posted_at"], name="internships_is_acti_5f99a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internship",
            index=models.Index(fields=["type"], name="internships_type_07b502_idx"),
        ),
        migrations.AddIndex(
            model_name="internship",
            index=models.Index(
                fields=["internship_type"], name="internships_interns_88e740_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internship",
            index=models.Index(
                fields=["category"], name="internships_categor_51260d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internship",
            index=models.Index(
                fields=["company"], name="internships_company_83aaf7_idx"
            ),
        ),
        migrations.AddField(
            model_name="internshipview",
            name="internship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_logs",
                to="internships.internship",
            ),
        ),
        migrations.AddField(
            model_name="internshipview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
